- name: Run database
  docker_container:
    name: my-db
    image: mrykse/tp-devops-database
    env:
      POSTGRES_DB=db
      POSTGRES_USER=user
      POSTGRES_PASSWORD=pwd
    networks:
      - name: my-network
  vars:
    ansible_python_interpreter: /usr/bin/python3