---
- name : Copying file
  ansible.builtin.copy:
    src: ./roles/launching/tasks/.env
    dest: /home/centos/.env
- name: Run App
  ansible.builtin.shell:
    name: launching
    cmd: docker run mrykse/tp-devops-simple-api --env-file /home/centos/.env --net my-network api
