- name: Run app
  docker_container:
    name: my-api
    image: mrykse/tp-devops-simple-api
    env:
      MYAPP_HOME=/opt/myapp
    networks:
      - name: my-network
  vars:
    ansible_python_interpreter: /usr/bin/python3