- name: Run proxy
  docker_container:
    name: my-proxy
    image: mrykse/tp-devops-httpd
    networks:
      - name: my-network
    published_ports:
      - "81:80"
  vars:
    ansible_python_interpreter: /usr/bin/python3